### ISSUE TITLE
Address register value difference

### ISSUE THREAD

**Issue by tsujido3r** [TamojitSaha/MAX6626_library#4]
Hi @TamojitSaha,

From the MAX6626 datasheet i see that the address bits are as below:
![image](https://user-images.githubusercontent.com/17527921/81983276-65954000-9633-11ea-8fce-afc76b48db0a.png)

but you have defined it altered it slightly. Is that intentional for some reason or is it a bug?

![image](https://user-images.githubusercontent.com/17527921/81983333-8198e180-9633-11ea-94b9-4e61b0c23bcd.png)

Thanks in advance.

**Comment by TamojitSaha** [comment]
Hey @tsujido3r 
Thanks a lot for pointing that out. I am actually surprised to see that I made such a dumb mistake.
I would really love to have a PR after correcting that issue.

**Comment by TamojitSaha** [comment]
Hello @tsujido3r and @per1234 
I have updated the incorrect i2c address.
So closing this issue as this was solved and due to lack of inactivity.
